apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: toggle-openapi-prefill
  title: Toggle booleans in openapi.yaml (prefilled, one commit)
  description: 'Prefills checkboxes from repo and lets dev change them; writes both in a single commit.'
spec:
  owner: group:default/platform
  type: utility

  parameters:
    - title: Repository
      required: [repoOwner, repo, branch]
      properties:
        repoOwner: { type: string, default: hadarkcommit }
        repo:      { type: string, default: idp-ingestion-example }
        branch:    { type: string, default: main }

    - title: Flags (prefilled from YAML)
      required: [toggles]
      properties:
        toggles:
          type: object
          ui:field: YamlBooleanToggles
          ui:options:
            ownerParam: repoOwner
            repoParam: repo
            branchParam: branch
            filePath: openapi.yaml
            fields:
              - { name: metadataNameFlag, title: 'metadata.name', path: 'metadata.name' }
              - { name: specTypeFlag,     title: 'spec.type',     path: 'spec.type' }

  steps:
    - id: commit
      name: Apply both changes as one commit
      action: github:file:yaml:commit:multi
      input:
        repoUrl: github.com?owner=${{ parameters.repoOwner }}&repo=${{ parameters.repo }}
        filePath: openapi.yaml
        changes:
          - yamlPath: metadata.name
            value: ${{ parameters.toggles.metadataNameFlag }}
          - yamlPath: spec.type
            value: ${{ parameters.toggles.specTypeFlag }}
        targetBranchName: ${{ parameters.branch }}
        commitMessage: >-
          chore(backstage): set metadata.name=${{ parameters.toggles.metadataNameFlag }},
          spec.type=${{ parameters.toggles.specTypeFlag }} in openapi.yaml

  output:
    links:
      - title: View commit
        url: ${{ steps.commit.output.commitUrl }}

