apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: toggle-openapi-fields-single-commit
  title: Toggle fields in openapi.yaml (single commit)
  description: 'Two checkboxes that set boolean values at metadata.name and spec.type, then push as one commit.'
spec:
  owner: group:default/platform
  type: utility

  parameters:
    - title: Target repository
      required: [repoOwner, repo, branch]
      properties:
        repoOwner:
          title: Owner/Org
          type: string
        repo:
          title: Repo
          type: string
        branch:
          title: Target branch
          type: string
          default: main

    - title: Pick fields to set (true/false)
      required: [metadataNameFlag, specTypeFlag]
      properties:
        metadataNameFlag:
          title: metadata.name → boolean
          type: boolean
          default: false
          description: 'If checked, set metadata.name to true; otherwise false.'
        specTypeFlag:
          title: spec.type → boolean
          type: boolean
          default: false
          description: 'If checked, set spec.type to true; otherwise false.'

  steps:
    - id: fetch
      name: Fetch repo
      action: fetch:plain
      input:
        url: https://github.com/${{ parameters.repoOwner }}/${{ parameters.repo }}/tree/${{ parameters.branch }}
        targetPath: repo

    - id: set-metadata
      name: Set metadata.name (workspace)
      action: yaml:set
      input:
        url: ./repo/openapi.yaml
        path: metadata.name
        value: ${{ parameters.metadataNameFlag }}

    - id: set-spec-type
      name: Set spec.type (workspace)
      action: yaml:set
      input:
        url: ./repo/openapi.yaml
        path: spec.type
        value: ${{ parameters.specTypeFlag }}

    # Single commit that includes both changes above
    - id: push
      name: Push changes as one commit
      action: github:repo:push
      input:
        repoUrl: github.com?owner=${{ parameters.repoOwner }}&repo=${{ parameters.repo }}
        branchName: ${{ parameters.branch }}
        commitMessage: >-
          chore(backstage): set metadata.name=${{ parameters.metadataNameFlag }}
          and spec.type=${{ parameters.specTypeFlag }} in openapi.yaml
        sourcePath: repo

  output:
    links:
      - title: View commit
        url: ${{ steps.push.output.commitUrl }}

