apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: toggle-openapi-booleans-direct-one-commit
  title: Toggle booleans in openapi.yaml (direct, one commit)
  description: 'Set booleans at metadata.name and spec.type in a single commit.'
spec:
  owner: group:default/platform
  type: utility

  parameters:
    - title: Target repository
      required: [repoOwner, repo, branch]
      properties:
        repoOwner: { type: string, default: hadarkcommit }
        repo:      { type: string, default: idp-ingestion-example }
        branch:    { type: string, default: main }

    - title: Pick fields
      required: [metadataNameFlag, specTypeFlag]
      properties:
        metadataNameFlag:
          type: boolean
          title: metadata.name → boolean
          default: false
        specTypeFlag:
          type: boolean
          title: spec.type → boolean
          default: false

  steps:
    - id: commit
      name: Apply both changes in one commit
      action: github:file:yaml:commit:multi
      input:
        repoUrl: github.com?owner=${{ parameters.repoOwner }}&repo=${{ parameters.repo }}
        filePath: openapi.yaml
        changes:
          - yamlPath: metadata.name
            value: ${{ parameters.metadataNameFlag }}
          - yamlPath: spec.type
            value: ${{ parameters.specTypeFlag }}
        targetBranchName: ${{ parameters.branch }}
        commitMessage: >-
          chore(backstage): set metadata.name=${{ parameters.metadataNameFlag }},
          spec.type=${{ parameters.specTypeFlag }} in openapi.yaml

  output:
    links:
      - title: View commit
        url: ${{ steps.commit.output.commitUrl }}
      - title: View file
        url: ${{ steps.commit.output.contentUrl }}

