apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: toggle-openapi-prefill
  title: Toggle booleans in openapi.yaml (prefilled, one commit)
spec:
  owner: group:default/platform
  type: utility

  parameters:
    - title: Repo
      required: [repoOwner, repo, branch]
      properties:
        repoOwner: { type: string, default: hadarkcommit }
        repo:      { type: string, default: idp-ingestion-example }
        branch:    { type: string, default: main }

    - title: Flags
      required: [metadataNameFlag, specTypeFlag]
      properties:
        metadataNameFlag:
          type: boolean
          title: metadata.name
          ui:field: YamlBooleanToggle
          ui:options:
            ownerParam: repoOwner
            repoParam: repo
            branchParam: branch
            filePath: openapi.yaml
            yamlPath: metadata.name
        specTypeFlag:
          type: boolean
          title: spec.type
          ui:field: YamlBooleanToggle
          ui:options:
            ownerParam: repoOwner
            repoParam: repo
            branchParam: branch
            filePath: openapi.yaml
            yamlPath: spec.type

  steps:
    - id: commit
      name: Apply both changes in one commit
      action: github:file:yaml:commit:multi
      input:
        repoUrl: github.com?owner=${{ parameters.repoOwner }}&repo=${{ parameters.repo }}
        filePath: openapi.yaml
        changes:
          - yamlPath: metadata.name
            value: ${{ parameters.metadataNameFlag }}
          - yamlPath: spec.type
            value: ${{ parameters.specTypeFlag }}
        targetBranchName: ${{ parameters.branch }}
        commitMessage: >-
          chore(backstage): set metadata.name=${{ parameters.metadataNameFlag }},
          spec.type=${{ parameters.specTypeFlag }} in openapi.yaml

  output:
    links:
      - title: View commit
        url: ${{ steps.commit.output.commitUrl }}

