apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: toggle-openapi-generic
  title: Toggle primary flag & multiple secondaries (Gitea)
  description: >
    Reads values from openapi.yaml; when primary is on, shows multiple string/boolean secondaries.
    Writes everything in one commit to Gitea.
spec:
  owner: group:default/platform
  type: utility

  parameters:
    - title: Flags (prefilled from YAML)
      required: [repoOwner, repo, branch, feature]
      properties:
        repoOwner: { type: string, default: hadarkr60, ui:widget: hidden, title: "" }
        repo:      { type: string, default: backstage-test, ui:widget: hidden, title: "" }
        branch:    { type: string, default: main, ui:widget: hidden, title: "" }

        feature:
          type: object
          title: "Feature controls"
          ui:field: YamlConditionalFields
          ui:options:
            host: gitea.com
            ownerParam: repoOwner
            repoParam: repo
            branchParam: branch
            filePath: openapi.yaml

            primary:
              booleanPath: metadata.name
              title: "Enable feature"

            strings:
              - path: spec.owner
                title: "Owner"
                choices: ["hadar", "no hadar"]

            booleans:
              - path: spec.type
                title: "Enable type"

  steps:
    - id: commit
      name: Apply changes in one commit (Gitea)
      action: gitea:file:yaml:commit:multi
      input:
        host: gitea.com
        owner:  ${{ parameters.repoOwner }}
        repo:   ${{ parameters.repo }}
        branch: ${{ parameters.branch }}
        filePath: openapi.yaml

        # what the field built for us
        changes: ${{ parameters.feature.changes }}

        # tell the action whether primary is on/off
        primaryEnabled: ${{ parameters.feature.enabled }}

        # when primary is DISABLED, force this exact default:
        defaultsWhenDisabled:
          - yamlPath: spec.owner
            value: "hadar"

        commitMessage: >-
          chore(backstage): update openapi.yaml via template "toggle-openapi-generic"

  output:
    links:
      - title: View file in Gitea
        url: https://gitea.com/${{ parameters.repoOwner }}/${{ parameters.repo }}/src/branch/${{ parameters.branch }}/openapi.yaml

