apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: toggle-openapi-generic
  title: Toggle primary flag & multiple secondaries (Gitea)
  description: >
    Reads values from openapi.yaml; when primary is on, shows multiple string/boolean secondaries.
    Writes everything in one commit to Gitea.
spec:
  owner: group:default/platform
  type: utility

  parameters:
    - title: Flags (prefilled from YAML)
      required: [repoOwner, repo, branch, feature]
      properties:
        # hidden repo coords
        repoOwner: { type: string, default: hadarkr60, ui:widget: hidden, title: "" }
        repo:      { type: string, default: backstage-test, ui:widget: hidden, title: "" }
        branch:    { type: string, default: main, ui:widget: hidden, title: "" }

        feature:
          type: object
          title: "Feature controls"
          ui:field: YamlConditionalFields
          ui:options:
            host: gitea.com
            ownerParam: repoOwner
            repoParam: repo
            branchParam: branch
            filePath: openapi.yaml

            primary:
              booleanPath: metadata.name
              title: "Enable feature"

            # configure ANY number of string fields
            strings:
              - path: spec.owner
                title: "Owner"
                choices: ["hadar", "no hadar"]
              # - path: spec.channel
              #   title: "Channel"
              #   choices: ["alpha", "beta", "stable"]

            # configure ANY number of boolean fields
            booleans:
              - path: spec.type
                title: "Enable type"
              # - path: spec.public
              #   title: "Public API"

  steps:
    - id: commit
      name: Apply changes in one commit (Gitea)
      action: gitea:file:yaml:commit:multi
      input:
        host: gitea.com
        owner:  ${{ parameters.repoOwner }}
        repo:   ${{ parameters.repo }}
        branch: ${{ parameters.branch }}
        filePath: openapi.yaml
        # 👇 The field outputs a ready-to-use `changes` array
        changes: ${{ parameters.feature.changes }}
        commitMessage: >-
          chore(backstage): update openapi.yaml via template "toggle-openapi-generic"

  output:
    links:
      - title: View file in Gitea
        url: https://gitea.com/${{ parameters.repoOwner }}/${{ parameters.repo }}/src/branch/${{ parameters.branch }}/openapi.yaml

